module X11::C
  # default keysyms
  XK_MISCELLANY   = true
  XK_XKB_KEYS     = true
  XK_3270         = false
  XK_LATIN1       = true
  XK_LATIN2       = true
  XK_LATIN3       = true
  XK_LATIN4       = true
  XK_LATIN8       = true
  XK_LATIN9       = true
  XK_CAUCASUS     = true
  XK_GREEK        = true
  XK_TECHNICAL    = false
  XK_SPECIAL      = false
  XK_PUBLISHING   = false
  XK_APL          = false
  XK_KATAKANA     = true
  XK_ARABIC       = true
  XK_CYRILLIC     = true
  XK_HEBREW       = true
  XK_THAI         = true
  XK_KOREAN       = true
  XK_ARMENIAN     = true
  XK_GEORGIAN     = true
  XK_VIETNAMESE   = true
  XK_CURRENCY     = true
  XK_MATHEMATICAL = true
  XK_BRAILLE      = true
  XK_SINHALA      = true
end # module X11
