name: Deploy docs
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Install shards
        run: shards update --ignore-crystal-version
      - name: Generate docs
        run: crystal doc
      - name: Deploy to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: docs
          commit_message: 'Generate docs: '